### ISSUE TITLE
DOCKER_USER ?

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2-docker#1]
Is `DOCKER_USER` a variable that the user should set? It is not set by docker on my machine. Running `export DOCKER_USER=mvexel && ./run_docker.sh` works.

**Comment by mgcuthbert** [comment]
Yes, I should modify it to use a default user name if not supplied.

**Comment by mgcuthbert** [comment]
I have resolved this in the latest checkin. You can provide the user as you have shown, however if you don't it will just default to "DEFAULT_USER"
