### ISSUE TITLE
retire or update https://hub.docker.com/r/matthieun/maproulette/

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2-docker#22]
Matthieu N uploaded https://hub.docker.com/r/matthieun/maproulette/ to docker hub when he first created it. We should probably (ask him to) remove it or else update it based on more recent work.

**Comment by mgcuthbert** [comment]
@matthieun

**Comment by matthieun** [comment]
Is there a new one I can link to in the comments?

**Comment by matthieun** [comment]
Unfortunately I don't think I can remove it from there.

**Comment by matthieun** [comment]
@mvexel @mgcuthbert I updated the comment.

**Comment by ljdelight** [comment]
@mvexel this one can be closed, the [hub repo readme](https://hub.docker.com/r/matthieun/maproulette) says it is deprecated and provides a link to maproulette2-docker
